FROM ubuntu:14.04

RUN apt-get update --yes
RUN apt-get install --yes software-properties-common apt-transport-https

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 68576280
RUN apt-add-repository --yes "deb https://deb.nodesource.com/node trusty main"

RUN apt-get update --yes
RUN apt-get install --yes --force-yes nodejs

EXPOSE 8443

RUN mkdir /tmp/build
ADD build /tmp/build

RUN chmod +x /tmp/build/backend.sh
CMD /tmp/build/backend.sh
